### PR TITLE
solana: fix swaps and use token 2022 mint for tests

### LINKED ISSUE #42: solana: add token 2022 mint to swap tests

### PR DESCRIPTION
**Pull request by a5-pickle**
Much wow.

Closes #42.

### CODE REVIEW

File: solana/programs/swap-layer/src/processor/initiate/swap/exact_in.rs [hunk 1]
```diff
@@ -27,39 +27,28 @@ pub struct InitiateSwapExactIn<'info> {
...
     ///
     /// This account will be closed by the end of the instruction.
-    #[account(
-        mut,
-        close = prepared_by,
-    )]
+    #[account(mut)]
     staged_outbound: Account<'info, StagedOutbound>,
 
     /// This custody token account will be closed by the end of the instruction.
```
Comment (gator-boi) [inline solana/programs/swap-layer/src/processor/initiate/swap/exact_in.rs:33]: This one too

File: solana/programs/swap-layer/src/processor/initiate/swap/exact_in.rs [hunk 2]
```diff
@@ -105,7 +94,9 @@ pub struct InitiateSwapExactIn<'info> {
     dst_swap_token: Box<Account<'info, token::TokenAccount>>,
 
     /// This account must be verified as the source mint for the swap.
-    #[account(address = staged_custody_token.mint)]
+    ///
+    /// NOTE: This is mutable in case we need to burn residual tokens.
```
Comment (gator-boi) [inline solana/programs/swap-layer/src/processor/initiate/swap/exact_in.rs:98]: Are the tokens ever burned? The residuals seems to go back to staged_custody_token.

File: solana/ts/scripts/collectedToAnchorToml.ts [hunk 3]
```diff
@@ -0,0 +1,14 @@
+import * as fs from "fs";
+
+main();
+
+async function main() {
+    fs.readdirSync("collected").forEach((fn) => {
+        const address = fn.slice(0, -5);
+        console.log(`
+### TODO
```
Comment (gator-boi) [inline solana/ts/scripts/collectedToAnchorToml.ts:9]: Do we need to leave this TODO in?

File: solana/ts/tests/10__swap.ts [hunk 4]
```diff
@@ -49,27 +51,44 @@ import {
...
 
+const JUPITER_V6_LUT_ADDRESSES_BERN = [
+    new PublicKey("2aGZxQimbQhRsvQhjvjXE35vZGJP2ajBSrUggoEwGGy4"),
+    new PublicKey("8Vaso6eE1pWktDHwy2qQBB1fhjmBgwzhoXQKe1sxtFjn"),
+    new PublicKey("BpQ5uMzQNWNgBCRNf6jffChhYMX5XVZuaoM4Rx16NCdf"),
+    new PublicKey("D6XNrxMsDoABJVVY5YyHxJuAB6WGzYCXpZeKyNtqu2v4"),
+    new PublicKey("55ir29U8MrZbGBV63XbbweEDXP9DSx7eNenc7hnTM81E"),
+];
+
+// const JUPITER_V6_LUT_ADDRESSES_BERN_OUT = [
```
Comment (gator-boi) [inline solana/ts/tests/10__swap.ts:86]: remove?

File: solana/ts/tests/10__swap.ts [hunk 5]
```diff
@@ -82,12 +101,10 @@ describe("Jupiter V6 Testing", () => {
...
     const matchingEngine = tokenRouter.matchingEngineProgram();
 
-    const luts: [PublicKey, PublicKey, PublicKey, PublicKey] = [
-        PublicKey.default,
-        PublicKey.default,
-        JUPITER_V6_LUT_ADDRESSES[0],
-        JUPITER_V6_LUT_ADDRESSES[1],
-    ];
+    const luts: PublicKey[] = [PublicKey.default];
+    for (let i = 0; i < JUPITER_V6_LUT_ADDRESSES.length; ++i) {
```
Comment (gator-boi) [inline solana/ts/tests/10__swap.ts:105]: Look at all those luts

**Review by gator-boi — APPROVED** [review]
Nicely done.

File: solana/ts/scripts/collectedToAnchorToml.ts (hunk 3 above)
Comment (a5-pickle) [reply solana/ts/scripts/collectedToAnchorToml.ts:9]: This TODO is actually for the Anchor.toml when someone pastes these entries in there (because we don't know how to label them at this point). I thought this was better than writing "Auto-generated" because it doesn't put any onus on the guy to label these after the fact.

Is that all right?

File: solana/ts/tests/10__swap.ts (hunk 5 above)
Comment (a5-pickle) [reply solana/ts/tests/10__swap.ts:105]: :chicken:

File: solana/programs/swap-layer/src/processor/initiate/swap/exact_in.rs [hunk 6]
```diff
@@ -27,39 +27,28 @@ pub struct InitiateSwapExactIn<'info> {
     /// the transfer.
     ///
     /// This account will be closed by the end of the instruction.
```
[the remark this answers is not in the document]
Comment (a5-pickle) [reply solana/programs/swap-layer/src/processor/initiate/swap/exact_in.rs]: Fixed here: https://github.com/wormholelabs-xyz/swap-layer/pull/62/commits/ec6cd4d84cf7805d7e760b683a3359ce149af15d#diff-6ab032298731fedd8da9185f721035324708e2ef941246502accff9f5cded932R29

File: solana/programs/swap-layer/src/processor/initiate/swap/exact_in.rs (hunk 2 above)
Comment (a5-pickle) [reply solana/programs/swap-layer/src/processor/initiate/swap/exact_in.rs]: Woops, good catch. I removed mut here: https://github.com/wormholelabs-xyz/swap-layer/pull/62/commits/ec6cd4d84cf7805d7e760b683a3359ce149af15d#diff-6ab032298731fedd8da9185f721035324708e2ef941246502accff9f5cded932L97-L99.

I accidentally left this here when I was trying to figure out what to do with the dust after a Jupiter swap.

And now that this is worked out, there is a path to perform an "Exact Out" the same way... something to tackle later.

File: solana/ts/tests/10__swap.ts (hunk 4 above)
Comment (a5-pickle) [reply solana/ts/tests/10__swap.ts]: Removed here: https://github.com/wormholelabs-xyz/swap-layer/pull/62/commits/ec6cd4d84cf7805d7e760b683a3359ce149af15d#diff-c38ab12451743ead3e8c769cd666ce42aaa94c8cf0ca92c8967973cb4144d0b4L86-L91

File: solana/ts/scripts/collectedToAnchorToml.ts (hunk 3 above)
Comment (gator-boi) [reply solana/ts/scripts/collectedToAnchorToml.ts:9]: ahh ok, that's fine
